### ISSUE TITLE
IAG task fails when SELinux is disabled

### ISSUE THREAD

**Issue by steven-schattenberg-itential** [itential/deployer#32]
This task will fail when SELinux is disabled.

```
- name: Allow IAG to listen on tcp port {{ iag_port }}
  community.general.seport:
    ports: "{{ iag_port }}"
    proto: tcp
    setype: http_port_t
    state: present
```

Add a conditional to check if SELinux is running.  If it is disabled then skip this task.
